name: Add contributors
on: [push, pull_request]

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: BobAnkh/add-contributors@v0.2.2
      with:
        CONTRIBUTOR: '### Author and contributors'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        COMMIT_MESSAGE: 'docs(README): update contributors'
        IMG_WIDTH: '40'